server:
  port: 8090

spring:
  kafka:
    consumer:
      bootstrap-servers: http://132.226.19.57:9093
    producer:
      bootstrap-servers: http://132.226.19.57:9093

slack:
  token: xoxb-3483719637124-3483748863972-ToUGtgboGQ7GKmezuzFn7H32
  channel:
    monitor: error
